name: lufickapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_pdfview: ^1.3.2
  flutter_timezone: ^4.0.0
  rxdart: ^0.28.0
  flutter_cache_manager: ^3.4.1
  supabase_flutter: ^2.8.3
  neopop: ^1.0.2
  form_field_validator: ^1.1.0
  form_validator: ^1.0.1
  file_picker: ^8.1.7
  flutter_riverpod: ^2.6.1
  riverpod: ^2.6.1
  clipboard: ^0.1.3
  supabase: ^2.6.2
  flutter_date_picker_timeline: ^0.3.1
  flip_card: ^0.7.0
  flutter_tts: ^4.2.0
  flutter_gemini: ^3.0.0
  pdf: ^3.11.1
  intl: ^0.17.0
  open_file: ^3.3.2
  local_auth: ^2.3.0
  table_calendar: ^3.0.8
  fl_chart: ^0.69.2
  firebase_analytics: ^11.3.6
  flutter_flow_chart: ^3.2.1
  flutter_svg: ^2.0.5
  animate_do: ^3.3.4
  marquee: ^2.3.0
  shimmer: ^3.0.0
  http: ^1.2.2
  firebase_app_check: ^0.3.2+2
  flutter_inappwebview: ^6.0.0
  google_sign_in: ^5.0.7
  rive: ^0.13.3
  flutter_spinkit: ^5.2.1
  colorful_progress_indicators: ^1.0.2
  colorful_circular_progress_indicator: ^0.0.2
  gap: ^3.0.1
  sqflite: ^2.2.0+3
  path_provider: ^2.0.13
  shared_preferences: ^2.3.3
  path: ^1.9.0
  share_plus: ^10.1.2
  highlight_text: ^1.8.0
  lottie: ^3.0.0
  cloud_firestore: ^5.5.1
  firebase_storage: ^12.3.7
  particles_flutter: ^1.0.1
  fluttertoast: ^8.2.8
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.5.0
  youtube_player_flutter: ^9.0.4
  firebase_core: ^3.7.0
  image_picker: ^1.1.2
  flutter_zoom_drawer: ^3.2.0
  flutter_speed_dial: ^6.0.0
  get: ^4.6.6
  video_player: ^2.9.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  flutter_screenutil: ^5.9.3
  firebase_auth: ^5.3.2
  url_launcher: ^6.1.7
  arkit_plugin: ^1.1.0
  get_storage: ^2.1.1  # Fixed syntax error

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - android/app/google-services.json
    - assets/images/
    - lib/Supabase/auth_api/
    - lib/Event Reminder App/Riverpod_Management/
